# Find avcodec
find_library(FFMPEG_AVCODEC_LIBRARY NAMES libavcodec avcodec)
find_path(FFMPEG_AVCODEC_INCLUDEDIR NAMES libavcodec/avcodec.h)

# Find avformat
find_library(FFMPEG_AVFORMAT_LIBRARY NAMES libavformat avformat)
find_path(FFMPEG_AVFORMAT_INCLUDEDIR NAMES libavformat/avformat.h)

# Find avutil
find_library(FFMPEG_AVUTIL_LIBRARY NAMES libavutil avutil)
find_path(FFMPEG_AVUTIL_INCLUDEDIR NAMES libavutil/avutil.h)

set(FFMPEG_LIBRARIES ${FFMPEG_AVCODEC_LIBRARY} ${FFMPEG_AVFORMAT_LIBRARY} ${FFMPEG_AVUTIL_LIBRARY})
set(FFMPEG_INCLUDE_DIRS ${FFMPEG_AVCODEC_INCLUDE_DIR} ${FFMPEG_AVFORMAT_INCLUDE_DIR} ${FFMPEG_AVUTIL_INCLUDE_DIR})

# Did we find everything?
set(FFMPEG_FOUND OFF)

if (FFMPEG_AVCODEC_LIBRARY STREQUAL FFMPEG_AVCODEC_LIBRARY-NOTFOUND OR
        FFMPEG_AVCODEC_INCLUDE_DIR STREQUAL FFMPEG_AVCODEC_INCLUDE_DIR-NOTFOUND OR
        
        FFMPEG_AVFORMAT_LIBRARY STREQUAL FFMPEG_AVFORMAT_LIBRARY-NOTFOUND OR
        FFMPEG_AVFORMAT_INCLUDE_DIR STREQUAL FFMPEG_AVFORMAT_INCLUDE_DIR-NOTFOUND OR
        
        FFMPEG_AVUTIL_LIBRARY STREQUAL FFMPEG_AVUTIL_LIBRARY-NOTFOUND OR
        FFMPEG_AVUTIL_INCLUDE_DIR STREQUAL FFMPEG_AVUTIL_INCLUDE_DIR-NOTFOUND)
    message(STATUS "Couldn't find FFmpeg")
else ()
    message(STATUS "Found FFmpeg: ${FFMPEG_AVCODEC_LIBRARY} ${FFMPEG_AVFORMAT_LIBRARY} ${FFMPEG_AVUTIL_LIBRARY}")
    set(FFMPEG_FOUND ON)
endif ()
